name:                necklace
version:             0.1.0.0
github:              "githubuser/necklace"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md
- src/Compiler/Lexer.x
- src/Compiler/Parser.y

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/necklace#readme>

dependencies:
- base >= 4.7 && < 5
- text
- array
- containers
- mtl
- lens
- llvm-hs-pure
- llvm-hs-pretty
- llvm-hs
- bytestring
- utf8-string
- process
- shelltestrunner-1.9

library:
  source-dirs: src

executables:
  necklace-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - necklace

tests:
  necklace-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - necklace
    - hspec

build-tools: 
  - alex
  - happy
